title: PCR Method Repository
description: A collection of cool PCR methods
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

url: https://just-the-docs.github.io
#logo: "/assets/images/web.png"
aux_links:
  Home: https://pauliusbaltrusis.github.io/PCR
nav:
  - Home: /PCR
  - About: /about
  - ddPCR:
    - Basics:
      - Amplitude Multiplexing: /Mds/PCR-method-library/Basics/Amplitude-multiplexing
      - Basics of Quantification and Digital PCR Assay Design: /Mds/PCR-method-library/Basics/Basics-of-quantification-and-digital-PCR-assay-design
      - Control Sample Types in ddPCR: /Mds/PCR-method-library/Basics/Control-sample-types-in-ddPCR
      - Most Common Sample Types in ddPCR: /Mds/PCR-method-library/Basics/Most-common-sample-types-in-ddPCR
      - Nucleic Acid Recovery from Droplets: /Mds/PCR-method-library/Basics/Nucleic-Acid-Recovery-From-Droplets
      - Primer and Probe Design: /Mds/PCR-method-library/Basics/Primer-and-Probe-design
    - Optimization:
      - Dark pProbes: /Mds/PCR-method-library/Optimization/Dark-probes
      - Establishing Limit of Blank Detection Quantification: /Mds/PCR-method-library/Optimization/Establishing-Limit-of-Blank-Detection-Quantification
      - General Best Practises for Running ddPCR and Multiplexing: /Mds/PCR-method-library/Optimization/General-best-practises-for-running-ddPCR-and-multiplexing
      - Locked-Nucleic Acids & Degenerate bases: /Mds/PCR-method-library/Optimization/Locked-Nucleic-Acids-and-Degenerate-bases
      - Rainbow Probes: /Mds/PCR-method-library/Optimization/Rainbow-Probes
      - Singleplex Multiplex ddPCR Reaction Optimization: /Mds/PCR-method-library/Optimization/Singleplex-Multiplex-ddPCR-Reaction-Optimization
    - DNA-based ddPCR Methods:
      - Allelic Imbalance for Copy Number Determination: /Mds/PCR-method-library/DNA-based-methods/Allelic-Imbalance-for-CNV
      - CAR-T Therapy:  /Mds/PCR-method-library/DNA-based-methods/CAR-T-Therapy
      - Drop-off Probes: /Mds/PCR-method-library/DNA-based-methods/Drop-off-Probes
      - Gene Editing with CRISPR/Cas: /Mds/PCR-method-library/DNA-based-methods/Gene-Editing-with-CRISPR-Cas
      - Gene Linkage EHEC Example: /Mds/PCR-method-library/DNA-based-methods/Gene-linkage-EHEC-example
      - Linkage and Phasing: /Mds/PCR-method-library/DNA-based-methods/Linkage-and-Phasing
      - Long Amplicon (LA) ddPCR: /Mds/PCR-method-library/DNA-based-methods/Long-Amplicon-(LA)-ddPCR
      - Mediator-Probe-ddPCR: /Mds/PCR-method-library/DNA-based-methods/Mediator-Probe-ddPCR
      - Methylation: /Mds/PCR-method-library/DNA-based-methods/Methylation
      - Mutant Enrichment via Blocker Displacement Amplification: /Mds/PCR-method-library/DNA-based-methods/Mutant-Enrichment-Blocker-Displacement-Amplification
      - Mutation Detection with Amplitude Multiplexing: /Mds/PCR-method-library/DNA-based-methods/Mutation-Detection-with-Amplitude-Multiplexing
      - Mutation Selected Amplification ddPCR: /Mds/PCR-method-library/DNA-based-methods/Mutation-Selected-Amplification-ddPCR
      - Quantifying Alive vs Dead Cells with ddPCR: /Mds/PCR-method-library/DNA-based-methods/Quantifying-Alive-vs-Dead-Cells-with-ddPCR
      - Simplified Multiplexing Strategies for Mutation Detection: /Mds/PCR-method-library/DNA-based-methods/Simplified-Multiplexing-Strategies-for-Mutation-Detection
      - Single-cell Vector Copy Number Variation Analyses: /Mds/PCR-method-library/DNA-based-methods/Single-cell-Vector-Copy-Number-variation-analyses
      - Structural Variants: /Mds/PCR-method-library/DNA-based-methods/Structural-variants
      - Super Selective Primer Mediated Mutant Enrichment: /Mds/PCR-method-library/DNA-based-methods/Super-Selective-Primer-Mediated-Mutant-Enrichment
      - Ultra-Rapid ddPCR: /Mds/PCR-method-library/DNA-based-methods/Ultra-Rapid-ddPCR
    - RNA and Protein-based ddPCR Methods:
      - Integrity of long RNA: /Mds/PCR-method-library/RNA and Protein-based methods/Integrity-of-long-RNA
      - Ligation Probes for miRNA Quantification: /Mds/PCR-method-library/RNA and Protein-based methods/Ligation-Probes-for-miRNA-Quantification
      - Quantification of Extracellular Vesicles: /Mds/PCR-method-library/RNA and Protein-based methods/Quantification-of-Extracellular-Vesicles
      - Selfie-dPCR: /Mds/PCR-method-library/RNA and Protein-based methods/Selfie-dPCR
      - Single Cell RNA & Protein Quantification: /Mds/PCR-method-library/RNA and Protein-based methods/Single-cell-RNA-and-Protein-Quantification
      - Single Cell Mutant RNA Enrichment: /Mds/PCR-method-library/RNA and Protein-based methods/Single-Cell-Mutant-RNA-Enrichment
      - Single Cell Transcript Profiling and Radial Multiplexing: /Mds/PCR-method-library/RNA and Protein-based methods/Single-Cell-Transcript-Profiling-and-Radial-Multiplexing
      - Wastewater Monitoring: /Mds/PCR-method-library/RNA and Protein-based methods/Wastewater-Monitoring
    - Post-reading Analysis:
  - qPCR Methods:
    - Gene Expression Assay Setup: /Mds/PCR-method-library/qPCR/Gene-expression-reaction-setup
    - Mediator Probe PCR: /Mds/PCR-method-library/qPCR/Mediator-Probe-qPCR
    - Molecular Beacons: /Mds/PCR-method-library/qPCR/Molecular-Beacons
    - Scorpion Probes: /Mds/PCR-method-library/qPCR/Scorpion-Probes
    - T-Blocker qPCR: /Mds/PCR-method-library/qPCR/T-Blocker-qPCR
  - Isothermal Amplification Methods:
    - Hyperplex PCR: /Mds/PCR-method-library/Isothermal-amplification-methods/Hyperplex-PCR
    - LAMP: /Mds/PCR-method-library/Isothermal-amplification-methods/LAMP
    - RPA: /Mds/PCR-method-library/Isothermal-amplification-methods/RPA
    - SuperRCA: /Mds/PCR-method-library/Isothermal-amplification-methods/SuperRCA
